spring.application.name=spring_test_meteo

# URL API Reale Open-Meteo
meteo.api.base-url=https://api.open-meteo.com/v1
geo.api.base-url=https://geocoding-api.open-meteo.com/v1

# Alziamo i limiti per gestire i blocchi del firewall di Windows
spring.http.client.connect-timeout=5s
spring.http.client.read-timeout=10s